#!/bin/bash

VOLUME=`pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's/.* \([0-9][0-9]*\)%.*/\1/'`;
MUTE=`pactl list sinks | grep $'^\tMute:' | sed -e 's/.*\:\s\(.*\)/\1/'`;
SINK=`pactl list sinks | grep -oP '^Sink[[:space:]]#(\d+)' | sed -n "s/^Sink\s#\([[:digit:]]\+\).*$/\1/p"`

up() {
    if [ "$MUTE" == "yes" ]; then
        pactl set-sink-mute $SINK toggle;
    fi

    if [ "$VOLUME" -lt "100" ]; then
        pactl -- set-sink-volume $SINK +5%;
        notify-send -t 500 "Volume: $((VOLUME + 5))";
    else
        notify-send -t 500 "Volume: ${VOLUME}";
    fi
}

down() {
    if [ "$MUTE" == "yes" ]; then
        pactl set-sink-mute $SINK toggle;
    fi

    if [ "$VOLUME" -gt "0" ]; then
        pactl -- set-sink-volume $SINK -5%;
        notify-send -t 500 "Volume: $((VOLUME - 5))";
    else
        notify-send -t 500 "Volume: ${VOLUME}";
    fi
}

mute() {
    pactl set-sink-mute $SINK toggle
    if [ "$MUTE" == "yes" ]; then
        notify-send -t 500 "Mute: no"
    else
        notify-send -t 500 "Mute: yes"
    fi
}

case $1 in
'up')
  up
  ;;
'down')
  down
  ;;
'mute')
  mute
  ;;
esac
